/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AIChatResponse = IDL.Record({
  'action' : IDL.Opt(IDL.Text),
  'insight' : IDL.Opt(IDL.Text),
  'reply' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'onboardingComplete' : IDL.Bool,
  'income' : IDL.Nat,
  'goals' : IDL.Vec(IDL.Text),
  'riskProfile' : IDL.Text,
});
export const Portfolio = IDL.Text;
export const Transactions = IDL.Text;
export const ChatResponse = IDL.Record({
  'action' : IDL.Opt(IDL.Text),
  'reply' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'aiChat' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [AIChatResponse], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFinHealthScore' : IDL.Func([], [IDL.Nat], ['query']),
  'getPortfolio' : IDL.Func([], [Portfolio], ['query']),
  'getReferralCode' : IDL.Func([], [IDL.Text], ['query']),
  'getReferralCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getTransactions' : IDL.Func([], [Transactions], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'processChat' : IDL.Func([IDL.Text], [ChatResponse], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveFinHealthScore' : IDL.Func([IDL.Nat], [], []),
  'savePortfolio' : IDL.Func([Portfolio], [], []),
  'saveTransactions' : IDL.Func([Transactions], [], []),
  'setAIApiKey' : IDL.Func([IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'useReferralCode' : IDL.Func([IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AIChatResponse = IDL.Record({
    'action' : IDL.Opt(IDL.Text),
    'insight' : IDL.Opt(IDL.Text),
    'reply' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'onboardingComplete' : IDL.Bool,
    'income' : IDL.Nat,
    'goals' : IDL.Vec(IDL.Text),
    'riskProfile' : IDL.Text,
  });
  const Portfolio = IDL.Text;
  const Transactions = IDL.Text;
  const ChatResponse = IDL.Record({
    'action' : IDL.Opt(IDL.Text),
    'reply' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'aiChat' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [AIChatResponse], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFinHealthScore' : IDL.Func([], [IDL.Nat], ['query']),
    'getPortfolio' : IDL.Func([], [Portfolio], ['query']),
    'getReferralCode' : IDL.Func([], [IDL.Text], ['query']),
    'getReferralCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getTransactions' : IDL.Func([], [Transactions], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'processChat' : IDL.Func([IDL.Text], [ChatResponse], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveFinHealthScore' : IDL.Func([IDL.Nat], [], []),
    'savePortfolio' : IDL.Func([Portfolio], [], []),
    'saveTransactions' : IDL.Func([Transactions], [], []),
    'setAIApiKey' : IDL.Func([IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'useReferralCode' : IDL.Func([IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };