/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'onboardingComplete' : IDL.Bool,
  'income' : IDL.Nat,
  'goals' : IDL.Vec(IDL.Text),
  'riskProfile' : IDL.Text,
});
export const Portfolio = IDL.Text;
export const Transactions = IDL.Text;

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFinHealthScore' : IDL.Func([], [IDL.Nat], ['query']),
  'getPortfolio' : IDL.Func([], [Portfolio], ['query']),
  'getReferralCode' : IDL.Func([], [IDL.Text], ['query']),
  'getReferralCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getTransactions' : IDL.Func([], [Transactions], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveFinHealthScore' : IDL.Func([IDL.Nat], [], []),
  'savePortfolio' : IDL.Func([Portfolio], [], []),
  'saveTransactions' : IDL.Func([Transactions], [], []),
  'useReferralCode' : IDL.Func([IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'onboardingComplete' : IDL.Bool,
    'income' : IDL.Nat,
    'goals' : IDL.Vec(IDL.Text),
    'riskProfile' : IDL.Text,
  });
  const Portfolio = IDL.Text;
  const Transactions = IDL.Text;
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFinHealthScore' : IDL.Func([], [IDL.Nat], ['query']),
    'getPortfolio' : IDL.Func([], [Portfolio], ['query']),
    'getReferralCode' : IDL.Func([], [IDL.Text], ['query']),
    'getReferralCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getTransactions' : IDL.Func([], [Transactions], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveFinHealthScore' : IDL.Func([IDL.Nat], [], []),
    'savePortfolio' : IDL.Func([Portfolio], [], []),
    'saveTransactions' : IDL.Func([Transactions], [], []),
    'useReferralCode' : IDL.Func([IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };